<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>StardewDeckBridge</AssemblyName>
    <RootNamespace>StardewDeckBridge</RootNamespace>
    <Version>1.2.1</Version>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <EnableHarmony>false</EnableHarmony>
    <EnableModDeploy>false</EnableModDeploy>
    <EnableModZip>true</EnableModZip>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.4.0" />
  </ItemGroup>
</Project>
